services:
  # ==========================================
  # PRIMARY 1 (Port 3111)
  # ==========================================
  app-primary-1:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: hls-multiviewer-app-primary-1
    restart: unless-stopped
    ports:
      - "3111:3111"
    volumes:
      - ./data_primary_1:/app/data
    networks:
      - multiviewer
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  # ==========================================
  # EVENT 1 (Port 3115)
  # ==========================================
  app-event-1:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: hls-multiviewer-app-event-1
    restart: unless-stopped
    ports:
      - "3115:3111"
    volumes:
      - ./data_event_1:/app/data
    networks:
      - multiviewer
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  # ==========================================
  # KONTEN 1 (Port 3116)
  # ==========================================
  app-konten-1:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: hls-multiviewer-app-konten-1
    restart: unless-stopped
    ports:
      - "3116:3111"
    volumes:
      - ./data_konten_1:/app/data
    networks:
      - multiviewer
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

networks:
  multiviewer:
    driver: bridge
